In [181]:
import pandas as pd

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

movies = movies.merge(credits, on="title")

movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [182]:
movies = movies[["movie_id", "title", "overview", "genres", "keywords", "cast", "crew"]]

movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [183]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [184]:
movies.dropna(inplace=True)

In [185]:
movies.isna().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [186]:
movies["overview"] = movies["overview"].apply(lambda x:x.split())

In [187]:
movies.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

In [188]:
import ast

In [189]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i["name"])
    return L

In [190]:
movies["genres"] = movies["genres"].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [191]:
movies["keywords"] = movies["keywords"].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [192]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter != 3:
            L.append(i["name"])
            counter += 1
        else:
            break
    return L

In [193]:
movies["cast"] = movies["cast"].apply(convert3)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [194]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i["job"] == "Director":
            L.append(i["name"])
            break
    return L

In [195]:
movies["crew"] = movies["crew"].apply(fetch_director)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [196]:
movies["genres"] = movies["genres"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["keywords"] = movies["keywords"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["cast"] = movies["cast"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["crew"] = movies["crew"].apply(lambda x:[i.replace(" ", "") for i in x])
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [197]:
movies["tags"] = movies["overview"] + movies["genres"] + movies["keywords"] + movies["cast"] + movies["crew"]

In [198]:
movies[["title", "tags"]].head()

,title,tags
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [199]:
new_df = movies[["movie_id", "title", "tags"]]

In [200]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [201]:
new_df["tags"] = new_df['tags'].apply(lambda x:" ".join(x))

In [202]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [203]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [204]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [205]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [206]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [207]:
new_df['tags'] = new_df['tags'].apply(stem)

In [208]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [209]:
from sklearn.feature_extraction.text import CountVectorizer

In [210]:
cv = CountVectorizer(max_features=2500, stop_words="english")

In [211]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [212]:
vectors.shape

(4806, 2500)

In [213]:
from sklearn.metrics.pairwise import cosine_similarity

In [214]:
similarity = cosine_similarity(vectors)
new_df = new_df.head(500)
similarity = similarity[:500, :500]

In [215]:
similarity.shape

(500, 500)

In [216]:
new_df[new_df['title'] == "Batman Begins"].index[0]

np.int64(119)

In [217]:
similarity[119]

array([0.0492366 , 0.05252257, 0.1069045 , 0.29593202, 0.11470787,
       0.12377055, 0.02156655, 0.15652476, 0.05897678, 0.30920827,
       0.20924575, 0.1963961 , 0.11313708, 0.02      , 0.16499158,
       0.04170288, 0.07620008, 0.1114172 , 0.13926212, 0.04264014,
       0.25928149, 0.15      , 0.        , 0.        , 0.125     ,
       0.06761234, 0.07385489, 0.10314212, 0.02773501, 0.04082483,
       0.1492405 , 0.09733285, 0.        , 0.06172134, 0.        ,
       0.15430335, 0.06793662, 0.        , 0.16296434, 0.09847319,
       0.11470787, 0.11043153, 0.02264554, 0.08626622, 0.16222142,
       0.12510865, 0.05163978, 0.11046895, 0.07698004, 0.08320503,
       0.02540003, 0.03746343, 0.07071068, 0.06625892, 0.02773501,
       0.0164399 , 0.06666667, 0.02156655, 0.14757296, 0.05619515,
       0.21974011, 0.03429972, 0.19611614, 0.        , 0.14142136,
       0.40166321, 0.14142136, 0.02581989, 0.15811388, 0.1786474 ,
       0.0246183 , 0.12126781, 0.13608276, 0.        , 0.02132007,
       0.07745967, 0.04529108, 0.13058573, 0.02540003, 0.30618622,
       0.04472136, 0.06859943, 0.13949717, 0.06188527, 0.03849002,
       0.0758098 , 0.09847319, 0.        , 0.05443311, 0.06482037,
       0.03015113, 0.02721655, 0.1165543 , 0.02236068, 0.02948839,
       0.02208631, 0.13949717, 0.11043153, 0.13363062, 0.12909944,
       0.03333333, 0.11952286, 0.02062842, 0.17822656, 0.08164966,
       0.03015113, 0.03885143, 0.10910895, 0.06396021, 0.03162278,
       0.02132007, 0.02357023, 0.175     , 0.13251783, 0.09058216,
       0.20412415, 0.08528029, 0.        , 0.10366421, 1.        ,
       0.04588315, 0.08485281, 0.16035675, 0.04472136, 0.04      ,
       0.09961165, 0.12126781, 0.09931271, 0.05      , 0.17669044,
       0.14342743, 0.05      , 0.16681153, 0.10327956, 0.03015113,
       0.09258201, 0.12126781, 0.17888544, 0.07071068, 0.18569534,
       0.1650274 , 0.06172134, 0.11547005, 0.0808122 , 0.06974858,
       0.11046895, 0.04352858, 0.08164966, 0.03086067, 0.1086429 ,
       0.08638684, 0.03535534, 0.17780018, 0.09205746, 0.        ,
       0.15396007, 0.06188527, 0.10289915, 0.04417261, 0.06030227,
       0.07624929, 0.03015113, 0.03162278, 0.16733201, 0.21009029,
       0.15460414, 0.06793662, 0.11547005, 0.04588315, 0.06123724,
       0.05940885, 0.16681153, 0.03162278, 0.04264014, 0.16733201,
       0.        , 0.02828427, 0.03535534, 0.08834522, 0.03244428,
       0.14757296, 0.08528029, 0.24003968, 0.03202563, 0.04588315,
       0.11624764, 0.07627701, 0.0942809 , 0.04125685, 0.10954451,
       0.06      , 0.        , 0.04472136, 0.22857143, 0.09733285,
       0.02721655, 0.26295029, 0.21213203, 0.1016001 , 0.02208631,
       0.03429972, 0.03429972, 0.06030227, 0.16329932, 0.07171372,
       0.24748737, 0.2213267 , 0.13363062, 0.03651484, 0.13333333,
       0.28401878, 0.        , 0.13093073, 0.12675004, 0.05252257,
       0.12510865, 0.05897678, 0.18973666, 0.13719887, 0.05443311,
       0.        , 0.09299811, 0.09128709, 0.05080005, 0.12998674,
       0.20924575, 0.05443311, 0.02672612, 0.10206207, 0.05262348,
       0.12472191, 0.04313311, 0.21380899, 0.06324555, 0.02108185,
       0.0942809 , 0.05252257, 0.15075567, 0.21908902, 0.08703883,
       0.1       , 0.15756772, 0.13363062, 0.02324953, 0.12649111,
       0.1016001 , 0.21552636, 0.16329932, 0.10314212, 0.03086067,
       0.06324555, 0.        , 0.20976177, 0.06708204, 0.04649906,
       0.02294157, 0.        , 0.09561829, 0.0381385 , 0.05773503,
       0.02626129, 0.09176629, 0.12792043, 0.03086067, 0.20426487,
       0.02672612, 0.08834522, 0.12649111, 0.0492366 , 0.        ,
       0.09901475, 0.0942809 , 0.07745967, 0.1165543 , 0.18599622,
       0.07878386, 0.10954451, 0.14599928, 0.0492366 , 0.06188527,
       0.2       , 0.16      , 0.18      , 0.17232809, 0.06963106,
       0.1671258 , 0.17817416, 0.15      , 0.03086067, 0.14439897,
       0.03162278, 0.07171372, 0.16329932, 0.05547002, 0.        ,
       0.0246183 , 0.09205746, 0.0421637 , 0.14342743, 0.24567691,
       0.06793662, 0.06810052, 0.11313708, 0.14142136, 0.14142136,
       0.02020305, 0.10327956, 0.0805823 , 0.15075567, 0.05656854,
       0.07035975, 0.06793662, 0.13130643, 0.22156468, 0.11766968,
       0.05080005, 0.19802951, 0.06488857, 0.11046895, 0.06324555,
       0.03162278, 0.        , 0.0492366 , 0.05656854, 0.04649906,
       0.03015113, 0.02948839, 0.025     , 0.16329932, 0.025     ,
       0.02581989, 0.0421637 , 0.025     , 0.06882472, 0.04529108,
       0.17888544, 0.        , 0.08728716, 0.        , 0.24596748,
       0.02294157, 0.07620008, 0.04965635, 0.11046895, 0.05656854,
       0.08528029, 0.025     , 0.02540003, 0.09258201, 0.05252257,
       0.11470787, 0.1492405 , 0.        , 0.03885143, 0.12247449,
       0.14142136, 0.11547005, 0.10606602, 0.        , 0.11795356,
       0.07627701, 0.12909944, 0.06030227, 0.09128709, 0.12510865,
       0.02357023, 0.05345225, 0.06172134, 0.06324555, 0.07878386,
       0.11952286, 0.09058216, 0.14757296, 0.        , 0.1       ,
       0.04082483, 0.0942809 , 0.10540926, 0.05656854, 0.11441551,
       0.15491933, 0.04082483, 0.04472136, 0.13416408, 0.03086067,
       0.        , 0.1650274 , 0.18353259, 0.16865481, 0.06030227,
       0.        , 0.03429972, 0.05443311, 0.05252257, 0.1132277 ,
       0.04850713, 0.14      , 0.04649906, 0.10206207, 0.        ,
       0.02773501, 0.        , 0.15756772, 0.14729194, 0.05656854,
       0.1979899 , 0.05720776, 0.04850713, 0.12344268, 0.23190036,
       0.04417261, 0.05      , 0.025     , 0.02626129, 0.        ,
       0.12998674, 0.14770979, 0.03535534, 0.        , 0.04472136,
       0.10660036, 0.10783277, 0.02672612, 0.22478059, 0.05388159,
       0.09901475, 0.03356725, 0.        , 0.24557625, 0.025     ,
       0.04588315, 0.06546537, 0.06708204, 0.13867505, 0.02264554,
       0.03922323, 0.11785113, 0.04780914, 0.13416408, 0.14142136,
       0.02236068, 0.05163978, 0.0843274 , 0.17822656, 0.25927249,
       0.09299811, 0.1963961 , 0.06060915, 0.18898224, 0.075     ,
       0.22677868, 0.02324953, 0.02672612, 0.11624764, 0.02390457,
       0.0843274 , 0.08340577, 0.05252257, 0.05940885, 0.03162278,
       0.08834522, 0.02886751, 0.12344268, 0.02886751, 0.        ,
       0.03651484, 0.06859943, 0.06974858, 0.13608276, 0.14368424,
       0.11881771, 0.19425717, 0.02581989, 0.        , 0.07620008,
       0.11881771, 0.12060454, 0.09258201, 0.05669467, 0.01591115,
       0.02208631, 0.05      , 0.22223356, 0.02828427, 0.02721655,
       0.12700013, 0.11428571, 0.03086067, 0.11355499, 0.03779645,
       0.03333333, 0.17483146, 0.11043153, 0.18666912, 0.09733285,
       0.15075567, 0.16222142, 0.08846517, 0.06172134, 0.12909944])

In [218]:
list(enumerate(similarity[119]))

[(0, np.float64(0.0492365963917331)),
 (1, np.float64(0.05252257314388902)),
 (2, np.float64(0.10690449676496974)),
 (3, np.float64(0.2959320151246863)),
 (4, np.float64(0.1147078669352809)),
 (5, np.float64(0.12377054955105521)),
 (6, np.float64(0.02156655464068768)),
 (7, np.float64(0.15652475842498528)),
 (8, np.float64(0.05897678246195886)),
 (9, np.float64(0.3092082730095704)),
 (10, np.float64(0.20924574973887472)),
 (11, np.float64(0.19639610121239315)),
 (12, np.float64(0.1131370849898476)),
 (13, np.float64(0.02)),
 (14, np.float64(0.1649915822768611)),
 (15, np.float64(0.04170288281141495)),
 (16, np.float64(0.07620007620011429)),
 (17, np.float64(0.11141720290623111)),
 (18, np.float64(0.13926212476455826)),
 (19, np.float64(0.04264014327112209)),
 (20, np.float64(0.25928148942086576)),
 (21, np.float64(0.15)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (24, np.float64(0.12499999999999999)),
 (25, np.float64(0.06761234037828133)),
 (26, np.float64(0.07385489458759964)),
 (27, np.float64(0.10314212462587935)),
 (28, np.float64(0.02773500981126146)),
 (29, np.float64(0.040824829046386304)),
 (30, np.float64(0.1492405014489273)),
 (31, np.float64(0.09733285267845751)),
 (32, np.float64(0.0)),
 (33, np.float64(0.06172133998483677)),
 (34, np.float64(0.0)),
 (35, np.float64(0.1543033499620919)),
 (36, np.float64(0.06793662204867575)),
 (37, np.float64(0.0)),
 (38, np.float64(0.16296434287653336)),
 (39, np.float64(0.0984731927834662)),
 (40, np.float64(0.1147078669352809)),
 (41, np.float64(0.11043152607484655)),
 (42, np.float64(0.022645540682891915)),
 (43, np.float64(0.08626621856275073)),
 (44, np.float64(0.16222142113076252)),
 (45, np.float64(0.12510864843424485)),
 (46, np.float64(0.05163977794943222)),
 (47, np.float64(0.11046895414779881)),
 (48, np.float64(0.0769800358919501)),
 (49, np.float64(0.08320502943378438)),
 (50, np.float64(0.0254000254000381)),
 (51, np.float64(0.03746343246326776)),
 (52, np.float64(0.07071067811865475)),
 (53, np.float64(0.06625891564490793)),
 (54, np.float64(0.02773500981126146)),
 (55, np.float64(0.01643989873053573)),
 (56, np.float64(0.06666666666666668)),
 (57, np.float64(0.02156655464068768)),
 (58, np.float64(0.14757295747452437)),
 (59, np.float64(0.056195148694901643)),
 (60, np.float64(0.21974010622941428)),
 (61, np.float64(0.034299717028501764)),
 (62, np.float64(0.19611613513818404)),
 (63, np.float64(0.0)),
 (64, np.float64(0.1414213562373095)),
 (65, np.float64(0.40166320883712187)),
 (66, np.float64(0.1414213562373095)),
 (67, np.float64(0.02581988897471611)),
 (68, np.float64(0.15811388300841894)),
 (69, np.float64(0.1786474002526241)),
 (70, np.float64(0.02461829819586655)),
 (71, np.float64(0.12126781251816647)),
 (72, np.float64(0.13608276348795434)),
 (73, np.float64(0.0)),
 (74, np.float64(0.021320071635561044)),
 (75, np.float64(0.07745966692414832)),
 (76, np.float64(0.04529108136578383)),
 (77, np.float64(0.13058572501980212)),
 (78, np.float64(0.0254000254000381)),
 (79, np.float64(0.3061862178478973)),
 (80, np.float64(0.044721359549995794)),
 (81, np.float64(0.06859943405700353)),
 (82, np.float64(0.13949716649258315)),
 (83, np.float64(0.061885274775527604)),
 (84, np.float64(0.03849001794597505)),
 (85, np.float64(0.07580980435789034)),
 (86, np.float64(0.0984731927834662)),
 (87, np.float64(0.0)),
 (88, np.float64(0.05443310539518174)),
 (89, np.float64(0.06482037235521644)),
 (90, np.float64(0.030151134457776358)),
 (91, np.float64(0.02721655269759087)),
 (92, np.float64(0.11655430348287171)),
 (93, np.float64(0.022360679774997897)),
 (94, np.float64(0.02948839123097943)),
 (95, np.float64(0.02208630521496931)),
 (96, np.float64(0.13949716649258312)),
 (97, np.float64(0.11043152607484655)),
 (98, np.float64(0.13363062095621217)),
 (99, np.float64(0.12909944487358055)),
 (100, np.float64(0.03333333333333334)),
 (101, np.float64(0.11952286093343936)),
 (102, np.float64(0.02062842492517587)),
 (103, np.float64(0.17822655773580137)),
 (104, np.float64(0.08164965809277261)),
 (105, np.float64(0.030151134457776358)),
 (106, np.float64(0.03885143449429057)),
 (107, np.float64(0.10910894511799618)),
 (108, np.float64(0.06396021490668313)),
 (109, np.float64(0.03162277660168379)),
 (110, np.float64(0.021320071635561044)),
 (111, np.float64(0.023570226039551584)),
 (112, np.float64(0.175)),
 (113, np.float64(0.13251783128981584)),
 (114, np.float64(0.09058216273156766)),
 (115, np.float64(0.2041241452319315)),
 (116, np.float64(0.08528028654224418)),
 (117, np.float64(0.0)),
 (118, np.float64(0.10366421106976322)),
 (119, np.float64(1.0)),
 (120, np.float64(0.04588314677411236)),
 (121, np.float64(0.08485281374238571)),
 (122, np.float64(0.1603567451474546)),
 (123, np.float64(0.044721359549995794)),
 (124, np.float64(0.04)),
 (125, np.float64(0.09961164901835046)),
 (126, np.float64(0.12126781251816647)),
 (127, np.float64(0.09931270663228416)),
 (128, np.float64(0.049999999999999996)),
 (129, np.float64(0.17669044171975448)),
 (130, np.float64(0.14342743312012723)),
 (131, np.float64(0.049999999999999996)),
 (132, np.float64(0.1668115312456598)),
 (133, np.float64(0.10327955589886444)),
 (134, np.float64(0.030151134457776358)),
 (135, np.float64(0.09258200997725516)),
 (136, np.float64(0.12126781251816647)),
 (137, np.float64(0.17888543819998318)),
 (138, np.float64(0.07071067811865475)),
 (139, np.float64(0.18569533817705183)),
 (140, np.float64(0.16502739940140695)),
 (141, np.float64(0.06172133998483677)),
 (142, np.float64(0.11547005383792516)),
 (143, np.float64(0.08081220356417686)),
 (144, np.float64(0.06974858324629157)),
 (145, np.float64(0.11046895414779882)),
 (146, np.float64(0.043528575006600706)),
 (147, np.float64(0.08164965809277261)),
 (148, np.float64(0.030860669992418384)),
 (149, np.float64(0.10864289525102223)),
 (150, np.float64(0.08638684255813601)),
 (151, np.float64(0.035355339059327376)),
 (152, np.float64(0.17780017780026672)),
 (153, np.float64(0.09205746178983235)),
 (154, np.float64(0.0)),
 (155, np.float64(0.1539600717839002)),
 (156, np.float64(0.061885274775527604)),
 (157, np.float64(0.10289915108550529)),
 (158, np.float64(0.04417261042993862)),
 (159, np.float64(0.060302268915552716)),
 (160, np.float64(0.07624928516630233)),
 (161, np.float64(0.030151134457776358)),
 (162, np.float64(0.03162277660168379)),
 (163, np.float64(0.1673320053068151)),
 (164, np.float64(0.2100902925755561)),
 (165, np.float64(0.1546041365047852)),
 (166, np.float64(0.06793662204867575)),
 (167, np.float64(0.11547005383792516)),
 (168, np.float64(0.04588314677411236)),
 (169, np.float64(0.06123724356957946)),
 (170, np.float64(0.05940885257860046)),
 (171, np.float64(0.1668115312456598)),
 (172, np.float64(0.03162277660168379)),
 (173, np.float64(0.04264014327112209)),
 (174, np.float64(0.1673320053068151)),
 (175, np.float64(0.0)),
 (176, np.float64(0.0282842712474619)),
 (177, np.float64(0.035355339059327376)),
 (178, np.float64(0.08834522085987724)),
 (179, np.float64(0.0324442842261525)),
 (180, np.float64(0.14757295747452437)),
 (181, np.float64(0.08528028654224418)),
 (182, np.float64(0.24003967925959163)),
 (183, np.float64(0.03202563076101742)),
 (184, np.float64(0.04588314677411236)),
 (185, np.float64(0.11624763874381927)),
 (186, np.float64(0.07627700713964738)),
 (187, np.float64(0.09428090415820634)),
 (188, np.float64(0.04125684985035174)),
 (189, np.float64(0.10954451150103323)),
 (190, np.float64(0.06)),
 (191, np.float64(0.0)),
 (192, np.float64(0.044721359549995794)),
 (193, np.float64(0.2285714285714286)),
 (194, np.float64(0.09733285267845751)),
 (195, np.float64(0.02721655269759087)),
 (196, np.float64(0.2629502940535666)),
 (197, np.float64(0.21213203435596423)),
 (198, np.float64(0.1016001016001524)),
 (199, np.float64(0.02208630521496931)),
 (200, np.float64(0.034299717028501764)),
 (201, np.float64(0.034299717028501764)),
 (202, np.float64(0.060302268915552716)),
 (203, np.float64(0.16329931618554522)),
 (204, np.float64(0.07171371656006362)),
 (205, np.float64(0.24748737341529164)),
 (206, np.float64(0.22132669799727464)),
 (207, np.float64(0.13363062095621217)),
 (208, np.float64(0.03651483716701107)),
 (209, np.float64(0.13333333333333336)),
 (210, np.float64(0.2840187787218772)),
 (211, np.float64(0.0)),
 (212, np.float64(0.13093073414159542)),
 (213, np.float64(0.12675004445952595)),
 (214, np.float64(0.05252257314388902)),
 (215, np.float64(0.12510864843424485)),
 (216, np.float64(0.05897678246195886)),
 (217, np.float64(0.18973665961010278)),
 (218, np.float64(0.13719886811400706)),
 (219, np.float64(0.05443310539518174)),
 (220, np.float64(0.0)),
 (221, np.float64(0.09299811099505542)),
 (222, np.float64(0.09128709291752768)),
 (223, np.float64(0.0508000508000762)),
 (224, np.float64(0.1299867367239363)),
 (225, np.float64(0.2092457497388747)),
 (226, np.float64(0.05443310539518174)),
 (227, np.float64(0.026726124191242435)),
 (228, np.float64(0.10206207261596575)),
 (229, np.float64(0.052623481158421755)),
 (230, np.float64(0.1247219128924647)),
 (231, np.float64(0.04313310928137536)),
 (232, np.float64(0.21380899352993948)),
 (233, np.float64(0.06324555320336758)),
 (234, np.float64(0.021081851067789197)),
 (235, np.float64(0.09428090415820634)),
 (236, np.float64(0.05252257314388902)),
 (237, np.float64(0.1507556722888818)),
 (238, np.float64(0.21908902300206645)),
 (239, np.float64(0.08703882797784891)),
 (240, np.float64(0.09999999999999999)),
 (241, np.float64(0.15756771943166706)),
 (242, np.float64(0.13363062095621217)),
 (243, np.float64(0.023249527748763855)),
 (244, np.float64(0.12649110640673517)),
 (245, np.float64(0.1016001016001524)),
 (246, np.float64(0.21552636243212986)),
 (247, np.float64(0.16329931618554522)),
 (248, np.float64(0.10314212462587935)),
 (249, np.float64(0.030860669992418384)),
 (250, np.float64(0.06324555320336758)),
 (251, np.float64(0.0)),
 (252, np.float64(0.2097617696340303)),
 (253, np.float64(0.0670820393249937)),
 (254, np.float64(0.04649905549752771)),
 (255, np.float64(0.02294157338705618)),
 (256, np.float64(0.0)),
 (257, np.float64(0.09561828874675149)),
 (258, np.float64(0.03813850356982369)),
 (259, np.float64(0.05773502691896258)),
 (260, np.float64(0.02626128657194451)),
 (261, np.float64(0.09176629354822471)),
 (262, np.float64(0.12792042981336627)),
 (263, np.float64(0.030860669992418384)),
 (264, np.float64(0.204264871994757)),
 (265, np.float64(0.026726124191242435)),
 (266, np.float64(0.08834522085987724)),
 (267, np.float64(0.12649110640673517)),
 (268, np.float64(0.0492365963917331)),
 (269, np.float64(0.0)),
 (270, np.float64(0.09901475429766743)),
 (271, np.float64(0.09428090415820634)),
 (272, np.float64(0.07745966692414832)),
 (273, np.float64(0.11655430348287171)),
 (274, np.float64(0.18599622199011084)),
 (275, np.float64(0.07878385971583353)),
 (276, np.float64(0.10954451150103323)),
 (277, np.float64(0.14599927901768628)),
 (278, np.float64(0.0492365963917331)),
 (279, np.float64(0.061885274775527604)),
 (280, np.float64(0.19999999999999998)),
 (281, np.float64(0.16)),
 (282, np.float64(0.18)),
 (283, np.float64(0.17232808737106586)),
 (284, np.float64(0.06963106238227913)),
 (285, np.float64(0.16712580435934665)),
 (286, np.float64(0.17817416127494956)),
 (287, np.float64(0.15)),
 (288, np.float64(0.030860669992418384)),
 (289, np.float64(0.14439897447623107)),
 (290, np.float64(0.03162277660168379)),
 (291, np.float64(0.07171371656006362)),
 (292, np.float64(0.16329931618554522)),
 (293, np.float64(0.05547001962252292)),
 (294, np.float64(0.0)),
 (295, np.float64(0.02461829819586655)),
 (296, np.float64(0.09205746178983235)),
 (297, np.float64(0.04216370213557839)),
 (298, np.float64(0.14342743312012723)),
 (299, np.float64(0.24567690745599768)),
 (300, np.float64(0.06793662204867575)),
 (301, np.float64(0.06810052246069989)),
 (302, np.float64(0.1131370849898476)),
 (303, np.float64(0.1414213562373095)),
 (304, np.float64(0.1414213562373095)),
 (305, np.float64(0.020203050891044214)),
 (306, np.float64(0.10327955589886444)),
 (307, np.float64(0.08058229640253803)),
 (308, np.float64(0.1507556722888818)),
 (309, np.float64(0.0565685424949238)),
 (310, np.float64(0.07035975447302918)),
 (311, np.float64(0.06793662204867575)),
 (312, np.float64(0.13130643285972254)),
 (313, np.float64(0.22156468376279895)),
 (314, np.float64(0.11766968108291043)),
 (315, np.float64(0.0508000508000762)),
 (316, np.float64(0.19802950859533486)),
 (317, np.float64(0.064888568452305)),
 (318, np.float64(0.11046895414779881)),
 (319, np.float64(0.06324555320336758)),
 (320, np.float64(0.03162277660168379)),
 (321, np.float64(0.0)),
 (322, np.float64(0.0492365963917331)),
 (323, np.float64(0.0565685424949238)),
 (324, np.float64(0.04649905549752771)),
 (325, np.float64(0.030151134457776358)),
 (326, np.float64(0.02948839123097943)),
 (327, np.float64(0.024999999999999998)),
 (328, np.float64(0.16329931618554522)),
 (329, np.float64(0.024999999999999998)),
 (330, np.float64(0.02581988897471611)),
 (331, np.float64(0.04216370213557839)),
 (332, np.float64(0.024999999999999998)),
 (333, np.float64(0.06882472016116853)),
 (334, np.float64(0.04529108136578383)),
 (335, np.float64(0.17888543819998318)),
 (336, np.float64(0.0)),
 (337, np.float64(0.08728715609439695)),
 (338, np.float64(0.0)),
 (339, np.float64(0.24596747752497686)),
 (340, np.float64(0.02294157338705618)),
 (341, np.float64(0.07620007620011429)),
 (342, np.float64(0.04965635331614207)),
 (343, np.float64(0.11046895414779881)),
 (344, np.float64(0.0565685424949238)),
 (345, np.float64(0.08528028654224418)),
 (346, np.float64(0.024999999999999998)),
 (347, np.float64(0.0254000254000381)),
 (348, np.float64(0.09258200997725516)),
 (349, np.float64(0.05252257314388902)),
 (350, np.float64(0.1147078669352809)),
 (351, np.float64(0.1492405014489273)),
 (352, np.float64(0.0)),
 (353, np.float64(0.03885143449429057)),
 (354, np.float64(0.1224744871391589)),
 (355, np.float64(0.1414213562373095)),
 (356, np.float64(0.11547005383792516)),
 (357, np.float64(0.10606601717798213)),
 (358, np.float64(0.0)),
 (359, np.float64(0.11795356492391772)),
 (360, np.float64(0.07627700713964738)),
 (361, np.float64(0.12909944487358055)),
 (362, np.float64(0.060302268915552716)),
 (363, np.float64(0.09128709291752768)),
 (364, np.float64(0.12510864843424485)),
 (365, np.float64(0.023570226039551584)),
 (366, np.float64(0.05345224838248487)),
 (367, np.float64(0.06172133998483677)),
 (368, np.float64(0.06324555320336758)),
 (369, np.float64(0.07878385971583353)),
 (370, np.float64(0.11952286093343936)),
 (371, np.float64(0.09058216273156766)),
 (372, np.float64(0.14757295747452437)),
 (373, np.float64(0.0)),
 (374, np.float64(0.1)),
 (375, np.float64(0.040824829046386304)),
 (376, np.float64(0.09428090415820634)),
 (377, np.float64(0.10540925533894599)),
 (378, np.float64(0.0565685424949238)),
 (379, np.float64(0.11441551070947109)),
 (380, np.float64(0.15491933384829665)),
 (381, np.float64(0.040824829046386304)),
 (382, np.float64(0.044721359549995794)),
 (383, np.float64(0.1341640786499874)),
 (384, np.float64(0.030860669992418384)),
 (385, np.float64(0.0)),
 (386, np.float64(0.16502739940140695)),
 (387, np.float64(0.18353258709644943)),
 (388, np.float64(0.16865480854231357)),
 (389, np.float64(0.060302268915552716)),
 (390, np.float64(0.0)),
 (391, np.float64(0.034299717028501764)),
 (392, np.float64(0.05443310539518174)),
 (393, np.float64(0.05252257314388902)),
 (394, np.float64(0.11322770341445958)),
 (395, np.float64(0.04850712500726659)),
 (396, np.float64(0.14)),
 (397, np.float64(0.04649905549752771)),
 (398, np.float64(0.10206207261596575)),
 (399, np.float64(0.0)),
 (400, np.float64(0.02773500981126146)),
 (401, np.float64(0.0)),
 (402, np.float64(0.15756771943166706)),
 (403, np.float64(0.14729193886373176)),
 (404, np.float64(0.0565685424949238)),
 (405, np.float64(0.1979898987322333)),
 (406, np.float64(0.05720775535473554)),
 (407, np.float64(0.04850712500726659)),
 (408, np.float64(0.12344267996967354)),
 (409, np.float64(0.23190036174568118)),
 (410, np.float64(0.04417261042993862)),
 (411, np.float64(0.049999999999999996)),
 (412, np.float64(0.024999999999999998)),
 (413, np.float64(0.02626128657194451)),
 (414, np.float64(0.0)),
 (415, np.float64(0.1299867367239363)),
 (416, np.float64(0.1477097891751993)),
 (417, np.float64(0.035355339059327376)),
 (418, np.float64(0.0)),
 (419, np.float64(0.044721359549995794)),
 (420, np.float64(0.10660035817780522)),
 (421, np.float64(0.1078327732034384)),
 (422, np.float64(0.026726124191242435)),
 (423, np.float64(0.22478059477960657)),
 (424, np.float64(0.05388159060803248)),
 (425, np.float64(0.09901475429766743)),
 (426, np.float64(0.03356725433186756)),
 (427, np.float64(0.0)),
 (428, np.float64(0.2455762454059682)),
 (429, np.float64(0.024999999999999998)),
 (430, np.float64(0.04588314677411236)),
 (431, np.float64(0.06546536707079771)),
 (432, np.float64(0.0670820393249937)),
 (433, np.float64(0.1386750490563073)),
 (434, np.float64(0.022645540682891915)),
 (435, np.float64(0.03922322702763681)),
 (436, np.float64(0.11785113019775792)),
 (437, np.float64(0.047809144373375745)),
 (438, np.float64(0.1341640786499874)),
 (439, np.float64(0.1414213562373095)),
 (440, np.float64(0.022360679774997897)),
 (441, np.float64(0.05163977794943222)),
 (442, np.float64(0.08432740427115679)),
 (443, np.float64(0.17822655773580137)),
 (444, np.float64(0.2592724864350674)),
 (445, np.float64(0.09299811099505542)),
 (446, np.float64(0.19639610121239315)),
 (447, np.float64(0.060609152673132646)),
 (448, np.float64(0.18898223650461363)),
 (449, np.float64(0.075)),
 (450, np.float64(0.22677868380553634)),
 (451, np.float64(0.023249527748763855)),
 (452, np.float64(0.026726124191242435)),
 (453, np.float64(0.11624763874381928)),
 (454, np.float64(0.023904572186687872)),
 (455, np.float64(0.08432740427115679)),
 (456, np.float64(0.0834057656228299)),
 (457, np.float64(0.05252257314388902)),
 (458, np.float64(0.05940885257860046)),
 (459, np.float64(0.03162277660168379)),
 (460, np.float64(0.08834522085987724)),
 (461, np.float64(0.02886751345948129)),
 (462, np.float64(0.12344267996967354)),
 (463, np.float64(0.02886751345948129)),
 (464, np.float64(0.0)),
 (465, np.float64(0.03651483716701107)),
 (466, np.float64(0.06859943405700353)),
 (467, np.float64(0.06974858324629157)),
 (468, np.float64(0.13608276348795434)),
 (469, np.float64(0.1436842416214199)),
 (470, np.float64(0.11881770515720091)),
 (471, np.float64(0.19425717247145285)),
 (472, np.float64(0.02581988897471611)),
 (473, np.float64(0.0)),
 (474, np.float64(0.07620007620011429)),
 (475, np.float64(0.11881770515720091)),
 (476, np.float64(0.12060453783110543)),
 (477, np.float64(0.09258200997725516)),
 (478, np.float64(0.056694670951384085)),
 (479, np.float64(0.0159111456835146)),
 (480, np.float64(0.02208630521496931)),
 (481, np.float64(0.049999999999999996)),
 (482, np.float64(0.22223355980148637)),
 (483, np.float64(0.0282842712474619)),
 (484, np.float64(0.02721655269759087)),
 (485, np.float64(0.1270001270001905)),
 (486, np.float64(0.1142857142857143)),
 (487, np.float64(0.030860669992418384)),
 (488, np.float64(0.11355499479153376)),
 (489, np.float64(0.03779644730092272)),
 (490, np.float64(0.03333333333333334)),
 (491, np.float64(0.17483145522430754)),
 (492, np.float64(0.11043152607484655)),
 (493, np.float64(0.1866691212406119)),
 (494, np.float64(0.09733285267845751)),
 (495, np.float64(0.1507556722888818)),
 (496, np.float64(0.16222142113076252)),
 (497, np.float64(0.08846517369293828)),
 (498, np.float64(0.06172133998483677)),
 (499, np.float64(0.12909944487358055))]

In [219]:
sorted(list(enumerate(similarity[119])), reverse=True, key=lambda x:x[1])

[(119, np.float64(1.0)),
 (65, np.float64(0.40166320883712187)),
 (9, np.float64(0.3092082730095704)),
 (79, np.float64(0.3061862178478973)),
 (3, np.float64(0.2959320151246863)),
 (210, np.float64(0.2840187787218772)),
 (196, np.float64(0.2629502940535666)),
 (20, np.float64(0.25928148942086576)),
 (444, np.float64(0.2592724864350674)),
 (205, np.float64(0.24748737341529164)),
 (339, np.float64(0.24596747752497686)),
 (299, np.float64(0.24567690745599768)),
 (428, np.float64(0.2455762454059682)),
 (182, np.float64(0.24003967925959163)),
 (409, np.float64(0.23190036174568118)),
 (193, np.float64(0.2285714285714286)),
 (450, np.float64(0.22677868380553634)),
 (423, np.float64(0.22478059477960657)),
 (482, np.float64(0.22223355980148637)),
 (313, np.float64(0.22156468376279895)),
 (206, np.float64(0.22132669799727464)),
 (60, np.float64(0.21974010622941428)),
 (238, np.float64(0.21908902300206645)),
 (246, np.float64(0.21552636243212986)),
 (232, np.float64(0.21380899352993948)),
 (197, np.float64(0.21213203435596423)),
 (164, np.float64(0.2100902925755561)),
 (252, np.float64(0.2097617696340303)),
 (10, np.float64(0.20924574973887472)),
 (225, np.float64(0.2092457497388747)),
 (264, np.float64(0.204264871994757)),
 (115, np.float64(0.2041241452319315)),
 (280, np.float64(0.19999999999999998)),
 (316, np.float64(0.19802950859533486)),
 (405, np.float64(0.1979898987322333)),
 (11, np.float64(0.19639610121239315)),
 (446, np.float64(0.19639610121239315)),
 (62, np.float64(0.19611613513818404)),
 (471, np.float64(0.19425717247145285)),
 (217, np.float64(0.18973665961010278)),
 (448, np.float64(0.18898223650461363)),
 (493, np.float64(0.1866691212406119)),
 (274, np.float64(0.18599622199011084)),
 (139, np.float64(0.18569533817705183)),
 (387, np.float64(0.18353258709644943)),
 (282, np.float64(0.18)),
 (137, np.float64(0.17888543819998318)),
 (335, np.float64(0.17888543819998318)),
 (69, np.float64(0.1786474002526241)),
 (103, np.float64(0.17822655773580137)),
 (443, np.float64(0.17822655773580137)),
 (286, np.float64(0.17817416127494956)),
 (152, np.float64(0.17780017780026672)),
 (129, np.float64(0.17669044171975448)),
 (112, np.float64(0.175)),
 (491, np.float64(0.17483145522430754)),
 (283, np.float64(0.17232808737106586)),
 (388, np.float64(0.16865480854231357)),
 (163, np.float64(0.1673320053068151)),
 (174, np.float64(0.1673320053068151)),
 (285, np.float64(0.16712580435934665)),
 (132, np.float64(0.1668115312456598)),
 (171, np.float64(0.1668115312456598)),
 (140, np.float64(0.16502739940140695)),
 (386, np.float64(0.16502739940140695)),
 (14, np.float64(0.1649915822768611)),
 (203, np.float64(0.16329931618554522)),
 (247, np.float64(0.16329931618554522)),
 (292, np.float64(0.16329931618554522)),
 (328, np.float64(0.16329931618554522)),
 (38, np.float64(0.16296434287653336)),
 (44, np.float64(0.16222142113076252)),
 (496, np.float64(0.16222142113076252)),
 (122, np.float64(0.1603567451474546)),
 (281, np.float64(0.16)),
 (68, np.float64(0.15811388300841894)),
 (241, np.float64(0.15756771943166706)),
 (402, np.float64(0.15756771943166706)),
 (7, np.float64(0.15652475842498528)),
 (380, np.float64(0.15491933384829665)),
 (165, np.float64(0.1546041365047852)),
 (35, np.float64(0.1543033499620919)),
 (155, np.float64(0.1539600717839002)),
 (237, np.float64(0.1507556722888818)),
 (308, np.float64(0.1507556722888818)),
 (495, np.float64(0.1507556722888818)),
 (21, np.float64(0.15)),
 (287, np.float64(0.15)),
 (30, np.float64(0.1492405014489273)),
 (351, np.float64(0.1492405014489273)),
 (416, np.float64(0.1477097891751993)),
 (58, np.float64(0.14757295747452437)),
 (180, np.float64(0.14757295747452437)),
 (372, np.float64(0.14757295747452437)),
 (403, np.float64(0.14729193886373176)),
 (277, np.float64(0.14599927901768628)),
 (289, np.float64(0.14439897447623107)),
 (469, np.float64(0.1436842416214199)),
 (130, np.float64(0.14342743312012723)),
 (298, np.float64(0.14342743312012723)),
 (64, np.float64(0.1414213562373095)),
 (66, np.float64(0.1414213562373095)),
 (303, np.float64(0.1414213562373095)),
 (304, np.float64(0.1414213562373095)),
 (355, np.float64(0.1414213562373095)),
 (439, np.float64(0.1414213562373095)),
 (396, np.float64(0.14)),
 (82, np.float64(0.13949716649258315)),
 (96, np.float64(0.13949716649258312)),
 (18, np.float64(0.13926212476455826)),
 (433, np.float64(0.1386750490563073)),
 (218, np.float64(0.13719886811400706)),
 (72, np.float64(0.13608276348795434)),
 (468, np.float64(0.13608276348795434)),
 (383, np.float64(0.1341640786499874)),
 (438, np.float64(0.1341640786499874)),
 (98, np.float64(0.13363062095621217)),
 (207, np.float64(0.13363062095621217)),
 (242, np.float64(0.13363062095621217)),
 (209, np.float64(0.13333333333333336)),
 (113, np.float64(0.13251783128981584)),
 (312, np.float64(0.13130643285972254)),
 (212, np.float64(0.13093073414159542)),
 (77, np.float64(0.13058572501980212)),
 (224, np.float64(0.1299867367239363)),
 (415, np.float64(0.1299867367239363)),
 (99, np.float64(0.12909944487358055)),
 (361, np.float64(0.12909944487358055)),
 (499, np.float64(0.12909944487358055)),
 (262, np.float64(0.12792042981336627)),
 (485, np.float64(0.1270001270001905)),
 (213, np.float64(0.12675004445952595)),
 (244, np.float64(0.12649110640673517)),
 (267, np.float64(0.12649110640673517)),
 (45, np.float64(0.12510864843424485)),
 (215, np.float64(0.12510864843424485)),
 (364, np.float64(0.12510864843424485)),
 (24, np.float64(0.12499999999999999)),
 (230, np.float64(0.1247219128924647)),
 (5, np.float64(0.12377054955105521)),
 (408, np.float64(0.12344267996967354)),
 (462, np.float64(0.12344267996967354)),
 (354, np.float64(0.1224744871391589)),
 (71, np.float64(0.12126781251816647)),
 (126, np.float64(0.12126781251816647)),
 (136, np.float64(0.12126781251816647)),
 (476, np.float64(0.12060453783110543)),
 (101, np.float64(0.11952286093343936)),
 (370, np.float64(0.11952286093343936)),
 (470, np.float64(0.11881770515720091)),
 (475, np.float64(0.11881770515720091)),
 (359, np.float64(0.11795356492391772)),
 (436, np.float64(0.11785113019775792)),
 (314, np.float64(0.11766968108291043)),
 (92, np.float64(0.11655430348287171)),
 (273, np.float64(0.11655430348287171)),
 (453, np.float64(0.11624763874381928)),
 (185, np.float64(0.11624763874381927)),
 (142, np.float64(0.11547005383792516)),
 (167, np.float64(0.11547005383792516)),
 (356, np.float64(0.11547005383792516)),
 (4, np.float64(0.1147078669352809)),
 (40, np.float64(0.1147078669352809)),
 (350, np.float64(0.1147078669352809)),
 (379, np.float64(0.11441551070947109)),
 (486, np.float64(0.1142857142857143)),
 (488, np.float64(0.11355499479153376)),
 (394, np.float64(0.11322770341445958)),
 (12, np.float64(0.1131370849898476)),
 (302, np.float64(0.1131370849898476)),
 (17, np.float64(0.11141720290623111)),
 (145, np.float64(0.11046895414779882)),
 (47, np.float64(0.11046895414779881)),
 (318, np.float64(0.11046895414779881)),
 (343, np.float64(0.11046895414779881)),
 (41, np.float64(0.11043152607484655)),
 (97, np.float64(0.11043152607484655)),
 (492, np.float64(0.11043152607484655)),
 (189, np.float64(0.10954451150103323)),
 (276, np.float64(0.10954451150103323)),
 (107, np.float64(0.10910894511799618)),
 (149, np.float64(0.10864289525102223)),
 (421, np.float64(0.1078327732034384)),
 (2, np.float64(0.10690449676496974)),
 (420, np.float64(0.10660035817780522)),
 (357, np.float64(0.10606601717798213)),
 (377, np.float64(0.10540925533894599)),
 (118, np.float64(0.10366421106976322)),
 (133, np.float64(0.10327955589886444)),
 (306, np.float64(0.10327955589886444)),
 (27, np.float64(0.10314212462587935)),
 (248, np.float64(0.10314212462587935)),
 (157, np.float64(0.10289915108550529)),
 (228, np.float64(0.10206207261596575)),
 (398, np.float64(0.10206207261596575)),
 (198, np.float64(0.1016001016001524)),
 (245, np.float64(0.1016001016001524)),
 (374, np.float64(0.1)),
 (240, np.float64(0.09999999999999999)),
 (125, np.float64(0.09961164901835046)),
 (127, np.float64(0.09931270663228416)),
 (270, np.float64(0.09901475429766743)),
 (425, np.float64(0.09901475429766743)),
 (39, np.float64(0.0984731927834662)),
 (86, np.float64(0.0984731927834662)),
 (31, np.float64(0.09733285267845751)),
 (194, np.float64(0.09733285267845751)),
 (494, np.float64(0.09733285267845751)),
 (257, np.float64(0.09561828874675149)),
 (187, np.float64(0.09428090415820634)),
 (235, np.float64(0.09428090415820634)),
 (271, np.float64(0.09428090415820634)),
 (376, np.float64(0.09428090415820634)),
 (221, np.float64(0.09299811099505542)),
 (445, np.float64(0.09299811099505542)),
 (135, np.float64(0.09258200997725516)),
 (348, np.float64(0.09258200997725516)),
 (477, np.float64(0.09258200997725516)),
 (153, np.float64(0.09205746178983235)),
 (296, np.float64(0.09205746178983235)),
 (261, np.float64(0.09176629354822471)),
 (222, np.float64(0.09128709291752768)),
 (363, np.float64(0.09128709291752768)),
 (114, np.float64(0.09058216273156766)),
 (371, np.float64(0.09058216273156766)),
 (497, np.float64(0.08846517369293828)),
 (178, np.float64(0.08834522085987724)),
 (266, np.float64(0.08834522085987724)),
 (460, np.float64(0.08834522085987724)),
 (337, np.float64(0.08728715609439695)),
 (239, np.float64(0.08703882797784891)),
 (150, np.float64(0.08638684255813601)),
 (43, np.float64(0.08626621856275073)),
 (116, np.float64(0.08528028654224418)),
 (181, np.float64(0.08528028654224418)),
 (345, np.float64(0.08528028654224418)),
 (121, np.float64(0.08485281374238571)),
 (442, np.float64(0.08432740427115679)),
 (455, np.float64(0.08432740427115679)),
 (456, np.float64(0.0834057656228299)),
 (49, np.float64(0.08320502943378438)),
 (104, np.float64(0.08164965809277261)),
 (147, np.float64(0.08164965809277261)),
 (143, np.float64(0.08081220356417686)),
 (307, np.float64(0.08058229640253803)),
 (275, np.float64(0.07878385971583353)),
 (369, np.float64(0.07878385971583353)),
 (75, np.float64(0.07745966692414832)),
 (272, np.float64(0.07745966692414832)),
 (48, np.float64(0.0769800358919501)),
 (186, np.float64(0.07627700713964738)),
 (360, np.float64(0.07627700713964738)),
 (160, np.float64(0.07624928516630233)),
 (16, np.float64(0.07620007620011429)),
 (341, np.float64(0.07620007620011429)),
 (474, np.float64(0.07620007620011429)),
 (85, np.float64(0.07580980435789034)),
 (449, np.float64(0.075)),
 (26, np.float64(0.07385489458759964)),
 (204, np.float64(0.07171371656006362)),
 (291, np.float64(0.07171371656006362)),
 (52, np.float64(0.07071067811865475)),
 (138, np.float64(0.07071067811865475)),
 (310, np.float64(0.07035975447302918)),
 (144, np.float64(0.06974858324629157)),
 (467, np.float64(0.06974858324629157)),
 (284, np.float64(0.06963106238227913)),
 (333, np.float64(0.06882472016116853)),
 (81, np.float64(0.06859943405700353)),
 (466, np.float64(0.06859943405700353)),
 (301, np.float64(0.06810052246069989)),
 (36, np.float64(0.06793662204867575)),
 (166, np.float64(0.06793662204867575)),
 (300, np.float64(0.06793662204867575)),
 (311, np.float64(0.06793662204867575)),
 (25, np.float64(0.06761234037828133)),
 (253, np.float64(0.0670820393249937)),
 (432, np.float64(0.0670820393249937)),
 (56, np.float64(0.06666666666666668)),
 (53, np.float64(0.06625891564490793)),
 (431, np.float64(0.06546536707079771)),
 (317, np.float64(0.064888568452305)),
 (89, np.float64(0.06482037235521644)),
 (108, np.float64(0.06396021490668313)),
 (233, np.float64(0.06324555320336758)),
 (250, np.float64(0.06324555320336758)),
 (319, np.float64(0.06324555320336758)),
 (368, np.float64(0.06324555320336758)),
 (83, np.float64(0.061885274775527604)),
 (156, np.float64(0.061885274775527604)),
 (279, np.float64(0.061885274775527604)),
 (33, np.float64(0.06172133998483677)),
 (141, np.float64(0.06172133998483677)),
 (367, np.float64(0.06172133998483677)),
 (498, np.float64(0.06172133998483677)),
 (169, np.float64(0.06123724356957946)),
 (447, np.float64(0.060609152673132646)),
 (159, np.float64(0.060302268915552716)),
 (202, np.float64(0.060302268915552716)),
 (362, np.float64(0.060302268915552716)),
 (389, np.float64(0.060302268915552716)),
 (190, np.float64(0.06)),
 (170, np.float64(0.05940885257860046)),
 (458, np.float64(0.05940885257860046)),
 (8, np.float64(0.05897678246195886)),
 (216, np.float64(0.05897678246195886)),
 (259, np.float64(0.05773502691896258)),
 (406, np.float64(0.05720775535473554)),
 (478, np.float64(0.056694670951384085)),
 (309, np.float64(0.0565685424949238)),
 (323, np.float64(0.0565685424949238)),
 (344, np.float64(0.0565685424949238)),
 (378, np.float64(0.0565685424949238)),
 (404, np.float64(0.0565685424949238)),
 (59, np.float64(0.056195148694901643)),
 (293, np.float64(0.05547001962252292)),
 (88, np.float64(0.05443310539518174)),
 (219, np.float64(0.05443310539518174)),
 (226, np.float64(0.05443310539518174)),
 (392, np.float64(0.05443310539518174)),
 (424, np.float64(0.05388159060803248)),
 (366, np.float64(0.05345224838248487)),
 (229, np.float64(0.052623481158421755)),
 (1, np.float64(0.05252257314388902)),
 (214, np.float64(0.05252257314388902)),
 (236, np.float64(0.05252257314388902)),
 (349, np.float64(0.05252257314388902)),
 (393, np.float64(0.05252257314388902)),
 (457, np.float64(0.05252257314388902)),
 (46, np.float64(0.05163977794943222)),
 (441, np.float64(0.05163977794943222)),
 (223, np.float64(0.0508000508000762)),
 (315, np.float64(0.0508000508000762)),
 (128, np.float64(0.049999999999999996)),
 (131, np.float64(0.049999999999999996)),
 (411, np.float64(0.049999999999999996)),
 (481, np.float64(0.049999999999999996)),
 (342, np.float64(0.04965635331614207)),
 (0, np.float64(0.0492365963917331)),
 (268, np.float64(0.0492365963917331)),
 (278, np.float64(0.0492365963917331)),
 (322, np.float64(0.0492365963917331)),
 (395, np.float64(0.04850712500726659)),
 (407, np.float64(0.04850712500726659)),
 (437, np.float64(0.047809144373375745)),
 (254, np.float64(0.04649905549752771)),
 (324, np.float64(0.04649905549752771)),
 (397, np.float64(0.04649905549752771)),
 (120, np.float64(0.04588314677411236)),
 (168, np.float64(0.04588314677411236)),
 (184, np.float64(0.04588314677411236)),
 (430, np.float64(0.04588314677411236)),
 (76, np.float64(0.04529108136578383)),
 (334, np.float64(0.04529108136578383)),
 (80, np.float64(0.044721359549995794)),
 (123, np.float64(0.044721359549995794)),
 (192, np.float64(0.044721359549995794)),
 (382, np.float64(0.044721359549995794)),
 (419, np.float64(0.044721359549995794)),
 (158, np.float64(0.04417261042993862)),
 (410, np.float64(0.04417261042993862)),
 (146, np.float64(0.043528575006600706)),
 (231, np.float64(0.04313310928137536)),
 (19, np.float64(0.04264014327112209)),
 (173, np.float64(0.04264014327112209)),
 (297, np.float64(0.04216370213557839)),
 (331, np.float64(0.04216370213557839)),
 (15, np.float64(0.04170288281141495)),
 (188, np.float64(0.04125684985035174)),
 (29, np.float64(0.040824829046386304)),
 (375, np.float64(0.040824829046386304)),
 (381, np.float64(0.040824829046386304)),
 (124, np.float64(0.04)),
 (435, np.float64(0.03922322702763681)),
 (106, np.float64(0.03885143449429057)),
 (353, np.float64(0.03885143449429057)),
 (84, np.float64(0.03849001794597505)),
 (258, np.float64(0.03813850356982369)),
 (489, np.float64(0.03779644730092272)),
 (51, np.float64(0.03746343246326776)),
 (208, np.float64(0.03651483716701107)),
 (465, np.float64(0.03651483716701107)),
 (151, np.float64(0.035355339059327376)),
 (177, np.float64(0.035355339059327376)),
 (417, np.float64(0.035355339059327376)),
 (61, np.float64(0.034299717028501764)),
 (200, np.float64(0.034299717028501764)),
 (201, np.float64(0.034299717028501764)),
 (391, np.float64(0.034299717028501764)),
 (426, np.float64(0.03356725433186756)),
 (100, np.float64(0.03333333333333334)),
 (490, np.float64(0.03333333333333334)),
 (179, np.float64(0.0324442842261525)),
 (183, np.float64(0.03202563076101742)),
 (109, np.float64(0.03162277660168379)),
 (162, np.float64(0.03162277660168379)),
 (172, np.float64(0.03162277660168379)),
 (290, np.float64(0.03162277660168379)),
 (320, np.float64(0.03162277660168379)),
 (459, np.float64(0.03162277660168379)),
 (148, np.float64(0.030860669992418384)),
 (249, np.float64(0.030860669992418384)),
 (263, np.float64(0.030860669992418384)),
 (288, np.float64(0.030860669992418384)),
 (384, np.float64(0.030860669992418384)),
 (487, np.float64(0.030860669992418384)),
 (90, np.float64(0.030151134457776358)),
 (105, np.float64(0.030151134457776358)),
 (134, np.float64(0.030151134457776358)),
 (161, np.float64(0.030151134457776358)),
 (325, np.float64(0.030151134457776358)),
 (94, np.float64(0.02948839123097943)),
 (326, np.float64(0.02948839123097943)),
 (461, np.float64(0.02886751345948129)),
 (463, np.float64(0.02886751345948129)),
 (176, np.float64(0.0282842712474619)),
 (483, np.float64(0.0282842712474619)),
 (28, np.float64(0.02773500981126146)),
 (54, np.float64(0.02773500981126146)),
 (400, np.float64(0.02773500981126146)),
 (91, np.float64(0.02721655269759087)),
 (195, np.float64(0.02721655269759087)),
 (484, np.float64(0.02721655269759087)),
 (227, np.float64(0.026726124191242435)),
 (265, np.float64(0.026726124191242435)),
 (422, np.float64(0.026726124191242435)),
 (452, np.float64(0.026726124191242435)),
 (260, np.float64(0.02626128657194451)),
 (413, np.float64(0.02626128657194451)),
 (67, np.float64(0.02581988897471611)),
 (330, np.float64(0.02581988897471611)),
 (472, np.float64(0.02581988897471611)),
 (50, np.float64(0.0254000254000381)),
 (78, np.float64(0.0254000254000381)),
 (347, np.float64(0.0254000254000381)),
 (327, np.float64(0.024999999999999998)),
 (329, np.float64(0.024999999999999998)),
 (332, np.float64(0.024999999999999998)),
 (346, np.float64(0.024999999999999998)),
 (412, np.float64(0.024999999999999998)),
 (429, np.float64(0.024999999999999998)),
 (70, np.float64(0.02461829819586655)),
 (295, np.float64(0.02461829819586655)),
 (454, np.float64(0.023904572186687872)),
 (111, np.float64(0.023570226039551584)),
 (365, np.float64(0.023570226039551584)),
 (243, np.float64(0.023249527748763855)),
 (451, np.float64(0.023249527748763855)),
 (255, np.float64(0.02294157338705618)),
 (340, np.float64(0.02294157338705618)),
 (42, np.float64(0.022645540682891915)),
 (434, np.float64(0.022645540682891915)),
 (93, np.float64(0.022360679774997897)),
 (440, np.float64(0.022360679774997897)),
 (95, np.float64(0.02208630521496931)),
 (199, np.float64(0.02208630521496931)),
 (480, np.float64(0.02208630521496931)),
 (6, np.float64(0.02156655464068768)),
 (57, np.float64(0.02156655464068768)),
 (74, np.float64(0.021320071635561044)),
 (110, np.float64(0.021320071635561044)),
 (234, np.float64(0.021081851067789197)),
 (102, np.float64(0.02062842492517587)),
 (305, np.float64(0.020203050891044214)),
 (13, np.float64(0.02)),
 (55, np.float64(0.01643989873053573)),
 (479, np.float64(0.0159111456835146)),
 (22, np.float64(0.0)),
 (23, np.float64(0.0)),
 (32, np.float64(0.0)),
 (34, np.float64(0.0)),
 (37, np.float64(0.0)),
 (63, np.float64(0.0)),
 (73, np.float64(0.0)),
 (87, np.float64(0.0)),
 (117, np.float64(0.0)),
 (154, np.float64(0.0)),
 (175, np.float64(0.0)),
 (191, np.float64(0.0)),
 (211, np.float64(0.0)),
 (220, np.float64(0.0)),
 (251, np.float64(0.0)),
 (256, np.float64(0.0)),
 (269, np.float64(0.0)),
 (294, np.float64(0.0)),
 (321, np.float64(0.0)),
 (336, np.float64(0.0)),
 (338, np.float64(0.0)),
 (352, np.float64(0.0)),
 (358, np.float64(0.0)),
 (373, np.float64(0.0)),
 (385, np.float64(0.0)),
 (390, np.float64(0.0)),
 (399, np.float64(0.0)),
 (401, np.float64(0.0)),
 (414, np.float64(0.0)),
 (418, np.float64(0.0)),
 (427, np.float64(0.0)),
 (464, np.float64(0.0)),
 (473, np.float64(0.0))]

In [220]:
sorted(list(enumerate(similarity[119])), reverse=True, key=lambda x:x[1])[1:6]

[(65, np.float64(0.40166320883712187)),
 (9, np.float64(0.3092082730095704)),
 (79, np.float64(0.3061862178478973)),
 (3, np.float64(0.2959320151246863)),
 (210, np.float64(0.2840187787218772))]

In [221]:
for i in sorted(list(enumerate(similarity[119])), reverse=True, key=lambda x:x[1])[1:6]:
    print(new_df.iloc[i[0]].title)

The Dark Knight
Batman v Superman: Dawn of Justice
Iron Man 2
The Dark Knight Rises
Batman & Robin

In [222]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [224]:
recommend("Avatar")

Jupiter Ascending
Beowulf
The Fifth Element
Edge of Tomorrow
The Twilight Saga: Breaking Dawn - Part 2

In [225]:
import pickle

In [226]:
pickle.dump(new_df, open("movies_list.pkl", "wb"))
pickle.dump(similarity, open("similarity.pkl", "wb"))